import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
function Contact() {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
    const handleSubmit = (e) => {
        e.preventDefault();
        alert('Thank you for reaching out! Your message has been submitted.');
    };
    return (_jsx("div", { className: "min-h-screen bg-gradient-to-r from-blue-500 via-purple-500 to-blue-500 flex items-center justify-center px-4", children: _jsxs("div", { className: "max-w-2xl w-full bg-white shadow-2xl rounded-lg p-10", children: [_jsx("h2", { className: "text-4xl font-extrabold text-center text-gray-800 mb-6", children: "Get in Touch" }), _jsx("p", { className: "text-center text-gray-600 mb-8", children: "Fill in the form below, and I\u2019ll get back to you shortly. Let\u2019s create something amazing together!" }), _jsxs("form", { onSubmit: handleSubmit, className: "space-y-6", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "name", className: "block text-lg font-medium text-gray-700 mb-2", children: "Your Name" }), _jsx("input", { type: "text", id: "name", value: name, onChange: (e) => setName(e.target.value), className: "w-full px-4 py-3 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-400 focus:border-transparent", placeholder: "Enter your full name", required: true })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "email", className: "block text-lg font-medium text-gray-700 mb-2", children: "Your Email" }), _jsx("input", { type: "email", id: "email", value: email, onChange: (e) => setEmail(e.target.value), className: "w-full px-4 py-3 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-400 focus:border-transparent", placeholder: "Enter your email address", required: true })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "message", className: "block text-lg font-medium text-gray-700 mb-2", children: "Your Message" }), _jsx("textarea", { id: "message", value: message, onChange: (e) => setMessage(e.target.value), className: "w-full px-4 py-3 border rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-purple-400 focus:border-transparent", rows: 5, placeholder: "Write your message here...", required: true })] }), _jsx("div", { className: "text-center", children: _jsx("button", { type: "submit", className: "w-full bg-gradient-to-r from-purple-500 to-blue-500 text-white font-bold py-3 rounded-lg shadow-md hover:from-purple-600 hover:to-blue-600 transition-transform transform hover:scale-105 focus:outline-none focus:ring-4 focus:ring-purple-300", children: "Send Message" }) })] })] }) }));
}
export default Contact;
